///|
pub extend QpackField with Eq::{equal, not_equal}

///|
pub extend QpackField with @debug.Debug::{to_repr}

///|
pub extend QpackLimits with Eq::{equal, not_equal}

///|
pub extend QpackLimits with @debug.Debug::{to_repr}

///|
pub extend QpackDecodeResult with Eq::{equal, not_equal}

///|
pub extend QpackDecodeResult with @debug.Debug::{to_repr}

///|
pub extend H3ErrorCode with Eq::{equal, not_equal}

///|
pub extend H3ErrorCode with @debug.Debug::{to_repr}

///|
pub extend Http3Error with Eq::{equal, not_equal}

///|
pub extend Http3Error with @debug.Debug::{to_repr}

///|
pub extend H3Setting with Eq::{equal, not_equal}

///|
pub extend H3Setting with @debug.Debug::{to_repr}

///|
pub extend Http3Frame with Eq::{equal, not_equal}

///|
pub extend Http3Frame with @debug.Debug::{to_repr}

///|
pub extend H3Role with Eq::{equal, not_equal}

///|
pub extend H3Role with @debug.Debug::{to_repr}

///|
pub extend H3UnidirectionalStream with Eq::{equal, not_equal}

///|
pub extend H3UnidirectionalStream with @debug.Debug::{to_repr}

///|
pub extend H3Settings with Eq::{equal, not_equal}

///|
pub extend H3Settings with @debug.Debug::{to_repr}

///|
pub extend H3IncomingMessage with Eq::{equal, not_equal}

///|
pub extend H3IncomingMessage with @debug.Debug::{to_repr}

///|
pub extend H3MessagePhase with Eq::{equal, not_equal}

///|
pub extend H3MessagePhase with @debug.Debug::{to_repr}

///|
pub extend H3FieldSectionKind with Eq::{equal, not_equal}

///|
pub extend H3FieldSectionKind with @debug.Debug::{to_repr}

///|
pub extend H3MessageMetadata with Eq::{equal, not_equal}

///|
pub extend H3MessageMetadata with @debug.Debug::{to_repr}

///|
pub extend H3Action with Eq::{equal, not_equal}

///|
pub extend H3Action with @debug.Debug::{to_repr}

///|
pub extend H3DriverAction with Eq::{equal, not_equal}

///|
pub extend H3DriverAction with @debug.Debug::{to_repr}
