///|
pub extend HpackHeader with Eq::{equal, not_equal}

///|
pub extend HpackHeader with @debug.Debug::{to_repr}

///|
pub extend H2ErrorCode with Eq::{equal, not_equal}

///|
pub extend H2ErrorCode with @debug.Debug::{to_repr}

///|
pub extend H2ProtocolError with Eq::{equal, not_equal}

///|
pub extend H2ProtocolError with @debug.Debug::{to_repr}

///|
pub extend H2Role with Eq::{equal, not_equal}

///|
pub extend H2Role with @debug.Debug::{to_repr}

///|
pub extend H2StreamState with Eq::{equal, not_equal}

///|
pub extend H2StreamState with @debug.Debug::{to_repr}
